### ISSUE TITLE
Problem with new screens of iPhones 6 and 6 Plus 

### ISSUE THREAD

**Issue by gdoliveira** [CEWendel/SWTableViewCell#244]
In the first loading of app, when you swipe cell, it does not show completely all buttons. Swipes stops before the end. Anyone can help me, please?

**Comment by spotlessicode** [comment]
Actually it doesn't work. I tested it for iphone5 (320 width), iphone6, 6+ and ipad too. Adn the problem is self.frame in the SWTableviewCell.m file, setFrame: functions. Because it's sometimes 320, sometimes 375, and not constantly 320 (fo example at iphone5). So I defined UScreen mainscree width, adn use that screenWidth instead of self.frame. So you don1t need layoutifNeeded, and BOOL WidhtChanged method, just easily this: frame.size.width = screenwidth;

**so 1. define:**

```
#define screenwidth [[UIScreen mainScreen]bounds].size.width
```

**2.: use screenwidth instead of self.frame at setFrame:**

```
- (void)setFrame:(CGRect)frame
{
    layoutUpdating = YES;
    // Fix for new screen sizes
    // Initially, the cell is still 320 points wide
    // We need to layout our subviews again when this changes so our constraints clip to the right width
    //BOOL widthChanged = (screenwidth != frame.size.width);
    frame.size.width = screenwidth;


    [super setFrame:frame];

    /*
    if (widthChanged)
    {
        [self layoutIfNeeded];
        NSLog(@"layout needed");
    }
     */
    layoutUpdating = NO;
}
```

**3.: here: - (void)updateCellState you need to change for screenWidth too:**

```
// Update the clipping on the utility button views according to the current position.
        CGRect frame = [self.contentView.superview convertRect:self.contentView.frame toView:self];
        frame.size.width = screenwidth;
        NSLog(@" updateCellState frame.size.width screenwidth %f", frame.size.width);

        self.leftUtilityClipConstraint.constant = MAX(0, CGRectGetMinX(frame) - CGRectGetMinX(self.frame));
        self.rightUtilityClipConstraint.constant = MIN(0, CGRectGetMaxX(frame) - CGRectGetMaxX(self.frame));
        NSLog(@" self.leftUtilityClipConstraint.constant %f", self.leftUtilityClipConstraint.constant);
        NSLog(@" self.rightUtilityClipConstraint.constant %f", self.rightUtilityClipConstraint.constant);
```

So finally it's working like a charm without any withButtonWidth, just simply: 

```
cell.rightUtilityButtons=rightUtilityButtons;
```

Tested on: iphone5 simulator (screenwidth:320), iphone 6 device (screenwidth:375) + simulator, iphone 6plus simulator (screenwidth:414), ipad Air simulator(screenwidth:768), ipadPro 12inch simulator(screenwidth:1024).
