### ISSUE TITLE
The view hierarchy is not prepared for the constraint

### ISSUE THREAD

**Issue by kyledecot** [CEWendel/SWTableViewCell#300]
I have subclassed `SWTableViewCell` and registered my nib w/ the tableview. When I run the application however I get the following the debug console

```
2015-03-24 21:58:42.852 ohio[18231:343586] The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x7fbed35b0890 SWUtilityButtonView:0x7fbed35afaa0.width <= UITableViewCellContentView:0x7fbed35acff0.width - 90>
    When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView _viewHierarchyUnpreparedForConstraint:] to debug.
2015-03-24 21:58:42.852 ohio[18231:343586] *** Assertion failure in -[ohio.ConnectionsTableViewCell _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:], /SourceCache/UIKit_Sim/UIKit-3347.16.1/NSLayoutConstraint_UIKitAdditions.m:560
```

The application doesn't crash but I don't see my cells. I'm using cocoapods and pulling from the github repo.

**Comment by scorpionking2k5** [comment]
I'm getting the same issue.

I have a subclassed SWTableViewCell as well. I tried assigning the utility buttons in my subclass instead of my view controller; but that doesn't work either.

```objective-c
The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x7ce8fa20 SWUtilityButtonView:0x7ce8f260.width <= UITableViewCellContentView:0x7ce8b4e0.width - 90>
	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView _viewHierarchyUnpreparedForConstraint:] to debug.
2015-04-17 07:41:46.437 Survey[4719:89849] *** Assertion failure in -[SavedItemCellView _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:], /SourceCache/UIKit_Sim/UIKit-3318.16.14/NSLayoutConstraint_UIKitAdditions.m:560
```
I'm using a zip download of the library.

**Comment by buhtr** [comment]
Got the same problem

**Comment by buhtr** [comment]
I've made a pull request to resolve this issue, if you need additional info don't hesitate to ask.

**Comment by confile** [comment]
+1

**Comment by weaglemobile** [comment]
Changing my nib from a UIView to a UITableViewCell resolved this for me. I think SWTableViewCell expects contentView to exist.

**Comment by buhtr** [comment]
weaglemobile do you get the point ? It is all about to use cell's view derived from SWTableViewCell (let it be ITMCellAlarm) from xib file in the following way:

1. Create a xib which contains you cell's view, indeed, it's top uiview have to be set to your class (i.e ITMCellAlarm) otherwise you cannot properly use it. 

2. Register the xib for you cell identifier (let it be 'baseCell') for you uitableview like that 
<pre><code>
[ self.tableView registerNib:[UINib nibWithNibName:@"viewCellAlarmBase" bundle:nil]
          forCellReuseIdentifier:@"baseCell" ];
</pre></code>
3. Try to reuse a cell from the nib like this 
<pre><code>
ITMCellAlarm * cell = (ITMCellAlarm*)[tableView dequeueReusableCellWithIdentifier:@"baseCell"
                                                                         forIndexPath:indexPath];
</pre></code>

After that you will definitely get this error. This is so because the SWTableViewCell expects the contentView of class UITableViewCellContent to be set and be a child of your class. In described approach the contentView.superview will be nil, that's why the view's hierarchy is broken and you get constraints problems as contentView is used in several places of SWTableViewCell.

In my pull request I've overcome it by properly parenting contentView and moving all view's childs to it with saving autolayout constraints.

**Comment by weaglemobile** [comment]
Yes. For your step #1 instead of dragging over a UIView for the top view in the nib I dragged a UITableViewCell. It worked bc it has contentView.

**Comment by buhtr** [comment]
Could You describe strep by step ? As far as I know when your create "new view file -> user interface ->view"  you get a nib with a top UIView which you cannot replace with UITableViewCell you just able to customize it's class. Do you place UITableViewCell in it ?

**Comment by weaglemobile** [comment]
No, after you create the new view file. Delete the default View at the top level and drag over a Table View Cell from the Object library. It should be at the top level.

**Comment by buhtr** [comment]
hm, it makes sense right now, didn't know about it, just tried it works, thanks a lot.

**Comment by canaksoy** [comment]
do not use registerNib and try using like:

```
    SWTableViewCell * cell;
    static NSString * reuseIdentifier = @"coCell";
    cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if (!cell) {
        cell = [[CommentsTableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
    }
```

**Comment by buhtr** [comment]
@canaksoy  you didn't get the point. The whole idea to have a view for a table's cell in a separate xib file. That is why you need to use a registerNib. In this case if you just use a UIView as a root in your xib file you will get this error, but if you use UITableViewCell (as @delvizis  has suggested) as a root everything is ok.

**Comment by ghost** [comment]
@buhtr How do you use UITableViewCell as root for the xib? The only way Xcode lets me create a new xib file is by choosing UIView. Is there a way to change the root?

**Comment by ghost** [comment]
I've just read what @delvizis wrote, to delete the default uiview and insert a uitableviewcell. Thanks!
